src/main/java/com/realdolmen/togethair/domain/Flight.java
package com.realdolmen.togethair.domain;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.persistence.*;
import javax.validation.constraints.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Created by GWTBF10 on 6/11/2017.
 */
@Entity
@ManagedBean
@RequestScoped
public class Flight implements Comparable<Flight>, Serializable{
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@NotNull
	@ManyToOne
	private FlightCompany flightCompany;
	
	@NotNull
	@OneToMany(fetch = FetchType.EAGER,orphanRemoval = true,mappedBy = "flight")
	private Set<Seat> seats = new HashSet<>();
	
	@NotNull
	@ManyToOne
	private Airport from;
	
	@NotNull
	@ManyToOne
	private Airport to;
	
	@NotNull
	@Digits(integer = 4, fraction = 0)
	private int flightCode;
	
	@NotNull
	@DecimalMin(value = "0")
	@DecimalMax(value = "1200")
	private int duration; //estimated travel time in min
	
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Future
	private Date departureDateTime;
	
	@ElementCollection(fetch = FetchType.EAGER)
	@MapKeyColumn(name="volumeDiscountNUmberOfTickets")
	@Column(name="volumeDiscountPercentage")
	@CollectionTable(name="volumeDiscounts", joinColumns=@JoinColumn(name="id"))
	private Map<Integer, Integer> volumeDiscounts= new HashMap<>();
	
	@NotNull
	@DecimalMax(value = "200")
	@DecimalMin(value = "50")
	private int priceOverridePercentage=100;
	
	@Version
	private int version;
	
	public int getFreeSeatsOfClass(TravelClass travelClass){
		int count =0;
		for(Seat s : seats){
			if(s.getTravelClassName()==travelClass && s.isAvailable())
				count++;
		}
		return count;
	}
	
	public float getPriceOfCheapestSeat() {
		float lowestPrice=0f;
		for(Seat s : seats){
			if(lowestPrice<s.getPrice())
				lowestPrice = s.getPrice();
		}
		return lowestPrice;
	}
	
	public float getPriceOfCheapestSeatOfClass(TravelClass tClass) {
		float lowestPrice=0f;
		for(Seat s : seats){
			if(lowestPrice<s.getPrice() && s.getTravelClassName()==tClass)
				lowestPrice = s.getPrice();
		}
		return lowestPrice;
	}

	public Long getId() {
		return id;
	}
	
	public int getFlightCode() {
		return flightCode;
	}
	
	public void setFlightCode(int flightCode) {
		this.flightCode = flightCode;
	}
	
	public int getDuration() {
		return duration;
	}
	
	public Map<Integer, Integer> getVolumeDiscounts() {
		return volumeDiscounts;
	}
	
	public void setVolumeDiscounts(Map<Integer, Integer> volumeDiscounts) {
		this.volumeDiscounts = volumeDiscounts;
	}
	
	public int getPriceOverridePercentage() {
		return priceOverridePercentage;
	}
	
	public void setPriceOverridePercentage(int priceOverridePercentage) {
		this.priceOverridePercentage = priceOverridePercentage;
	}
	
	public void setDuration(int duration) {
		this.duration = duration;
	}
	
	public FlightCompany getFlightCompany() {
		return flightCompany;
	}
	
	public void setFlightCompany(FlightCompany flightCompany) {
		this.flightCompany = flightCompany;
	}
	
	public Set<Seat> getSeats() {
		return seats;
	}

	public Set<Seat> getAvailableSeats(){
		return seats.stream()
				.filter(s -> s.isAvailable())
				.collect(Collectors.toSet());
	}

	public Seat getSeat(String location){
		for(Seat s : getSeats()){
			if(s.getLocation().equals(location)){
				return s;
			}
		}
		return null;
	}
	
	public void setSeats(Set<Seat> seats) {
		for (Seat s: seats) {
			addSeat(s);
		}
	}

	public void addSeat(Seat s){
		seats.add(s);
		s.setFlight(this);
	}
	
	public Airport getFrom() {
		return from;
	}
	
	public void setFrom(Airport from) {
		this.from = from;
	}
	
	public Airport getTo() {
		return to;
	}
	
	public void setTo(Airport to) {
		this.to = to;
	}
	
	public Date getDepartureDateTime() {
		return departureDateTime;
	}
	
	public void setDepartureDateTime(Date departureDateTime) {
		this.departureDateTime = departureDateTime;
	}
	
	@Override   //Compare on cheapest ticket
	public int compareTo(Flight f) {
		return Float.compare(this.getPriceOfCheapestSeat(),f.getPriceOfCheapestSeat());
	}
	
	public static Comparator<Flight> DateTimeComparator = (f1, f2) -> {
		LocalDateTime f1Date = LocalDateTime.ofInstant(f1.getDepartureDateTime().toInstant(), ZoneId.systemDefault());
		LocalDateTime f2Date = LocalDateTime.ofInstant(f2.getDepartureDateTime().toInstant(), ZoneId.systemDefault());
		
		return f1Date.compareTo(f2Date);
	};
	
	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		Flight flight = (Flight) o;

		if (id != flight.id) return false;
		if (from != null ? !from.equals(flight.from) : flight.from != null) return false;
		if (to != null ? !to.equals(flight.to) : flight.to != null) return false;
		return departureDateTime != null ? departureDateTime.equals(flight.departureDateTime) : flight.departureDateTime == null;
	}

	@Override
	public int hashCode() {
		int result = (int) (id ^ (id >>> 32));
		result = 31 * result + (from != null ? from.hashCode() : 0);
		result = 31 * result + (to != null ? to.hashCode() : 0);
		result = 31 * result + (departureDateTime != null ? departureDateTime.hashCode() : 0);
		return result;
	}
}

src/main/webapp/resources/pages/index-search.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition>
    <!--<h1>Home</h1>-->
    <div style="height: 7em;"/>
    <b:jumbotron styleClass="search-background">
        <h1>To Get Air</h1>
        <b:form horizontal="true">
            <!--<h2>Destination</h2>-->
            <b:formGroup>
                <b:inputText mediumScreen="full-width" placeholder="Brussels" typeahead="true"
                             typeaheadValues="Brussel"
                             fieldSize="lg"
                             value="#{searchBean.fromCityName}">
                    <f:facet name="prepend">
                        <h:outputText value="From" />
                    </f:facet>
                </b:inputText>
                <b:inputText mediumScreen="two-thirds" typeahead="true"
                             typeaheadValues="New York"
                             placeholder="Madrid"
                             render-label="false" fieldSize="lg"
                             value="#{searchBean.toCityName}">
                    <f:facet name="prepend">
                        <h:outputText value="To" />
                    </f:facet>
                </b:inputText>
                <b:inputText mediumScreen="one-third" mask="integer"
                             placeholder="Madrid"
                             render-label="false" fieldSize="lg"
                             value="#{searchBean.minNrOfSeats}">
                    <f:facet name="append">
                        <h:outputText value="Passengers" />
                    </f:facet>
                </b:inputText>
            </b:formGroup>
            <h3>Time Period</h3>
            <b:formGroup>
                <b:dateTimePicker mediumScreen="half"
                                  value="#{searchBean.date1}"
                                  showIcon="true"
                                  iconPosition="left"
                                  allowInputToggle="true"
                                  showDate="true"
                                  showTime="false"
                                  useCurrent="true"
                                  fieldSize="lg"
                                  placeholder="From"/>
                <b:dateTimePicker mediumScreen="half"
                                  value="#{searchBean.date2}"
                                  showIcon="true"
                                  iconPosition="left"
                                  allowInputToggle="true"
                                  showDate="true"
                                  showTime="false"
                                  useCurrent="true"
                                  fieldSize="lg"
                                  placeholder="Untill"/>
            </b:formGroup>
            <b:commandButton value="Search" look="success">
                <f:ajax listener="#{searchBean.search}"
                execute="@form"
                render="results"/>
            </b:commandButton>
        </b:form>
    </b:jumbotron>

    <b:form id="results">
        <b:jumbotron styleClass="search-background" rendered="#{not empty searchBean.searchResults}">
            <h2>Results</h2>
            <b:dataTable value="#{searchBean.searchResults}"
                         var="flight"
                         searching="false">

                <b:dataTableColumn value="#{flight.flightCompany}" label="provider"/>
                <b:dataTableColumn value="#{flight.flightCode}" label="flight code"/>
                <b:dataTableColumn value="#{flight.departureDateTime}" label="departure"/>
                <b:dataTableColumn value="#{flight.duration}" label="estimated duration"/>
                <b:dataTableColumn value="#{flight.priceOfCheapestSeat}"  label="price" order="asc"/>
                <b:dataTableColumn label="controls" >
                    <b:commandButton value="book" look="success" action="booking"/>
                    <h:inputHidden id="flightId" value="#{flight.id}"/>
                </b:dataTableColumn>

            </b:dataTable>
            <h:inputHidden id="nrOfPassengers" value="#{searchBean.minNrOfSeats}"/>
        </b:jumbotron>
    </b:form>
</ui:composition>
</html>

src/main/webapp/resources/pages/menu.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
<ui:composition>
    <b:navBar brand="To Get Air" position="bottom" sticky="true">
        <b:navbarLinks>
            <b:navLink value="Home" href="#"/>
            <b:navLink value="Link1" href="#"/>
            <b:navLink value="Link2" href="#"/>
            <b:navLink value="Link3" href="#"/>
            <b:form>
                <b:navCommandLink value="booking" action="booking" />
            </b:form>
            <h:form>
                <h:commandLink value="booking" action="booking"/>
            </h:form>
        </b:navbarLinks>
    </b:navBar>
</ui:composition>
</html>